[tool.poetry]
name = "paraminjector"
version = "0.1.0"
description = ""
authors = ["Joscha Götzer <joscha.goetzer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
cached-property = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
